<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2575.7">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #cacaca; -webkit-text-stroke: #cacaca; background-color: #171717}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #36c0a0; -webkit-text-stroke: #36c0a0; background-color: #171717}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #c27e65; -webkit-text-stroke: #c27e65; background-color: #171717}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #cacaca; -webkit-text-stroke: #cacaca; background-color: #171717; min-height: 14.0px}
    p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #d4d4d4; -webkit-text-stroke: #d4d4d4; background-color: #171717}
    p.p6 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #4f7b3d; -webkit-text-stroke: #4f7b3d; background-color: #171717}
    p.p7 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #4689cc; -webkit-text-stroke: #4689cc; background-color: #171717}
    span.s1 {font-kerning: none; color: #4689cc; -webkit-text-stroke: 0px #4689cc}
    span.s2 {font-kerning: none}
    span.s3 {font-kerning: none; color: #36c0a0; -webkit-text-stroke: 0px #36c0a0}
    span.s4 {font-kerning: none; color: #d4d4d4; -webkit-text-stroke: 0px #d4d4d4}
    span.s5 {font-kerning: none; color: #c27e65; -webkit-text-stroke: 0px #c27e65}
    span.s6 {font-kerning: none; color: #cacaca; -webkit-text-stroke: 0px #cacaca}
    span.s7 {font-kerning: none; color: #a7c598; -webkit-text-stroke: 0px #a7c598}
  </style>
</head>
<body>
<p class="p1"><span class="s1">import</span><span class="s2"> </span><span class="s3">React</span><span class="s4">,</span><span class="s2"> </span><span class="s4">{</span><span class="s2"> useState</span><span class="s4">,</span><span class="s2"> useEffect </span><span class="s4">}</span><span class="s2"> </span><span class="s1">from</span><span class="s2"> </span><span class="s5">'react'</span><span class="s4">;</span></p>
<p class="p2"><span class="s1">import</span><span class="s6"> </span><span class="s1">type</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s2">DailyEntry</span><span class="s4">,</span><span class="s6"> </span><span class="s2">SummaryData</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s5">'./types'</span><span class="s4">;</span></p>
<p class="p1"><span class="s1">import</span><span class="s2"> </span><span class="s4">{</span><span class="s2"> calculateSummaries </span><span class="s4">}</span><span class="s2"> </span><span class="s1">from</span><span class="s2"> </span><span class="s5">'./utils/calculations'</span><span class="s4">;</span></p>
<p class="p3"><span class="s1">import</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s3">Header</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s2">'./components/Header'</span><span class="s4">;</span></p>
<p class="p3"><span class="s1">import</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s3">SummaryDashboard</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s2">'./components/SummaryDashboard'</span><span class="s4">;</span></p>
<p class="p3"><span class="s1">import</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s3">EntryForm</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s2">'./components/EntryForm'</span><span class="s4">;</span></p>
<p class="p3"><span class="s1">import</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s3">Logbook</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s2">'./components/Logbook'</span><span class="s4">;</span></p>
<p class="p3"><span class="s1">import</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s3">Footer</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s2">'./components/Footer'</span><span class="s4">;</span></p>
<p class="p2"><span class="s1">import</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s2">PlusCircle</span><span class="s4">,</span><span class="s6"> </span><span class="s2">LogOut</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s1">from</span><span class="s6"> </span><span class="s5">'lucide-react'</span><span class="s4">;</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s1">const</span><span class="s2"> initialData</span><span class="s4">:</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s4">[]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> </span><span class="s4">[</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>date</span><span class="s4">:</span><span class="s2"> </span><span class="s5">"2024-07-20"</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>steps</span><span class="s4">:</span><span class="s2"> </span><span class="s7">24000</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>pushups</span><span class="s4">:</span><span class="s2"> </span><span class="s7">320</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>pullups</span><span class="s4">:</span><span class="s2"> </span><span class="s7">75</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>optionalExerciseName</span><span class="s4">:</span><span class="s2"> </span><span class="s5">"Squats"</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>optionalExerciseReps</span><span class="s4">:</span><span class="s2"> </span><span class="s7">100</span><span class="s4">,</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">        </span>comment</span><span class="s4">:</span><span class="s6"> </span><span class="s2">"Felt great today, really pushed the limits on the squats. The weather was perfect for a long walk."</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">},</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>date</span><span class="s4">:</span><span class="s2"> </span><span class="s5">"2024-07-19"</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>steps</span><span class="s4">:</span><span class="s2"> </span><span class="s7">22500</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>pushups</span><span class="s4">:</span><span class="s2"> </span><span class="s7">310</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>pullups</span><span class="s4">:</span><span class="s2"> </span><span class="s7">70</span><span class="s4">,</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">        </span>comment</span><span class="s4">:</span><span class="s6"> </span><span class="s2">"A bit tired, but managed to hit the goals. Consistency is key!"</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">},</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>date</span><span class="s4">:</span><span class="s2"> </span><span class="s5">"2024-07-18"</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>steps</span><span class="s4">:</span><span class="s2"> </span><span class="s7">25100</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>pushups</span><span class="s4">:</span><span class="s2"> </span><span class="s7">330</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>pullups</span><span class="s4">:</span><span class="s2"> </span><span class="s7">80</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>optionalExerciseName</span><span class="s4">:</span><span class="s2"> </span><span class="s5">"Lunges"</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>optionalExerciseReps</span><span class="s4">:</span><span class="s2"> </span><span class="s7">80</span><span class="s4">,</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">        </span>comment</span><span class="s4">:</span><span class="s6"> </span><span class="s2">"Amazing energy levels! Added some lunges to mix things up."</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">},</span></p>
<p class="p5"><span class="s2">];</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p2"><span class="s1">const</span><span class="s6"> </span><span class="s2">App</span><span class="s4">:</span><span class="s6"> </span><span class="s2">React</span><span class="s4">.</span><span class="s2">FC</span><span class="s6"> </span><span class="s4">=</span><span class="s6"> </span><span class="s4">()</span><span class="s6"> </span><span class="s4">=&gt;</span><span class="s6"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">entries</span><span class="s4">,</span><span class="s2"> setEntries</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">&lt;</span><span class="s3">DailyEntry</span><span class="s4">[]&gt;(()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">try</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s1">const</span><span class="s2"> savedEntries </span><span class="s4">=</span><span class="s2"> localStorage</span><span class="s4">.</span><span class="s2">getItem</span><span class="s4">(</span><span class="s5">'motionvationEntries'</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s1">return</span><span class="s2"> savedEntries </span><span class="s4">?</span><span class="s2"> </span><span class="s3">JSON</span><span class="s4">.</span><span class="s2">parse</span><span class="s4">(</span><span class="s2">savedEntries</span><span class="s4">)</span><span class="s2"> </span><span class="s4">:</span><span class="s2"> initialData</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span><span class="s2"> </span><span class="s1">catch</span><span class="s2"> </span><span class="s4">(</span><span class="s2">error</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">            </span>console</span><span class="s4">.</span><span class="s6">error</span><span class="s4">(</span><span class="s2">"Could not parse saved entries:"</span><span class="s4">,</span><span class="s6"> error</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s1">return</span><span class="s2"> initialData</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">});</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">summary</span><span class="s4">,</span><span class="s2"> setSummary</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">&lt;</span><span class="s3">SummaryData</span><span class="s4">&gt;(</span><span class="s2">calculateSummaries</span><span class="s4">(</span><span class="s2">entries</span><span class="s4">));</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">showForm</span><span class="s4">,</span><span class="s2"> setShowForm</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s1">false</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">isAuthenticated</span><span class="s4">,</span><span class="s2"> setIsAuthenticated</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">!!</span><span class="s2">sessionStorage</span><span class="s4">.</span><span class="s2">getItem</span><span class="s4">(</span><span class="s5">'motionvation_auth'</span><span class="s4">));</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">editingEntry</span><span class="s4">,</span><span class="s2"> setEditingEntry</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">&lt;</span><span class="s3">DailyEntry</span><span class="s2"> </span><span class="s4">|</span><span class="s2"> </span><span class="s1">null</span><span class="s4">&gt;(</span><span class="s1">null</span><span class="s4">);</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span>useEffect</span><span class="s4">(()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>localStorage</span><span class="s4">.</span><span class="s2">setItem</span><span class="s4">(</span><span class="s5">'motionvationEntries'</span><span class="s4">,</span><span class="s2"> </span><span class="s3">JSON</span><span class="s4">.</span><span class="s2">stringify</span><span class="s4">(</span><span class="s2">entries</span><span class="s4">));</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setSummary</span><span class="s4">(</span><span class="s2">calculateSummaries</span><span class="s4">(</span><span class="s2">entries</span><span class="s4">));</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">},</span><span class="s2"> </span><span class="s4">[</span><span class="s2">entries</span><span class="s4">]);</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> handleSaveEntry </span><span class="s4">=</span><span class="s2"> </span><span class="s4">(</span><span class="s2">entry</span><span class="s4">:</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s4">)</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">let</span><span class="s2"> newEntries</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">if</span><span class="s2"> </span><span class="s4">(</span><span class="s2">editingEntry</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>newEntries </span><span class="s4">=</span><span class="s2"> entries</span><span class="s4">.</span><span class="s2">map</span><span class="s4">(</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> e</span><span class="s4">.</span><span class="s2">date </span><span class="s4">===</span><span class="s2"> editingEntry</span><span class="s4">.</span><span class="s2">date </span><span class="s4">?</span><span class="s2"> entry </span><span class="s4">:</span><span class="s2"> e</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span><span class="s2"> </span><span class="s1">else</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>newEntries </span><span class="s4">=</span><span class="s2"> </span><span class="s4">[</span><span class="s2">entry</span><span class="s4">,</span><span class="s2"> </span><span class="s4">...</span><span class="s2">entries</span><span class="s4">];</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p4"><span class="s2"><span class="Apple-converted-space">        </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setEntries</span><span class="s4">(</span><span class="s2">newEntries</span><span class="s4">.</span><span class="s2">sort</span><span class="s4">((</span><span class="s2">a</span><span class="s4">,</span><span class="s2"> b</span><span class="s4">)</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s1">new</span><span class="s2"> </span><span class="s3">Date</span><span class="s4">(</span><span class="s2">b</span><span class="s4">.</span><span class="s2">date</span><span class="s4">).</span><span class="s2">getTime</span><span class="s4">()</span><span class="s2"> </span><span class="s4">-</span><span class="s2"> </span><span class="s1">new</span><span class="s2"> </span><span class="s3">Date</span><span class="s4">(</span><span class="s2">a</span><span class="s4">.</span><span class="s2">date</span><span class="s4">).</span><span class="s2">getTime</span><span class="s4">()));</span></p>
<p class="p4"><span class="s2"><span class="Apple-converted-space">        </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setShowForm</span><span class="s4">(</span><span class="s1">false</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setEditingEntry</span><span class="s4">(</span><span class="s1">null</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">};</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> handleEdit </span><span class="s4">=</span><span class="s2"> </span><span class="s4">(</span><span class="s2">entry</span><span class="s4">:</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s4">)</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setEditingEntry</span><span class="s4">(</span><span class="s2">entry</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setShowForm</span><span class="s4">(</span><span class="s1">true</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>window</span><span class="s4">.</span><span class="s2">scrollTo</span><span class="s4">({</span><span class="s2"> top</span><span class="s4">:</span><span class="s2"> </span><span class="s7">0</span><span class="s4">,</span><span class="s2"> behavior</span><span class="s4">:</span><span class="s2"> </span><span class="s5">'smooth'</span><span class="s2"> </span><span class="s4">});</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">};</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> handleDelete </span><span class="s4">=</span><span class="s2"> </span><span class="s4">(</span><span class="s2">date</span><span class="s4">:</span><span class="s2"> </span><span class="s1">string</span><span class="s4">)</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">        </span></span><span class="s1">if</span><span class="s6"> </span><span class="s4">(</span><span class="s6">window</span><span class="s4">.</span><span class="s6">confirm</span><span class="s4">(</span><span class="s2">"Bist du sicher, dass du diesen Eintrag löschen möchtest?"</span><span class="s4">))</span><span class="s6"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setEntries</span><span class="s4">(</span><span class="s2">entries</span><span class="s4">.</span><span class="s2">filter</span><span class="s4">(</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> e</span><span class="s4">.</span><span class="s2">date </span><span class="s4">!==</span><span class="s2"> date</span><span class="s4">));</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">};</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> handleToggleFormClick </span><span class="s4">=</span><span class="s2"> </span><span class="s4">()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">if</span><span class="s2"> </span><span class="s4">(!</span><span class="s2">isAuthenticated</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">            </span></span><span class="s1">const</span><span class="s6"> password </span><span class="s4">=</span><span class="s6"> prompt</span><span class="s4">(</span><span class="s2">"Bitte Passwort eingeben, um fortzufahren:"</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s1">if</span><span class="s2"> </span><span class="s4">(</span><span class="s2">password </span><span class="s4">===</span><span class="s2"> </span><span class="s5">'motion2024'</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span><span class="s2"><span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span>sessionStorage</span><span class="s4">.</span><span class="s2">setItem</span><span class="s4">(</span><span class="s5">'motionvation_auth'</span><span class="s4">,</span><span class="s2"> </span><span class="s5">'true'</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span>setIsAuthenticated</span><span class="s4">(</span><span class="s1">true</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span>setEditingEntry</span><span class="s4">(</span><span class="s1">null</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span>setShowForm</span><span class="s4">(</span><span class="s1">true</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s4">}</span><span class="s2"> </span><span class="s1">else</span><span class="s2"> </span><span class="s1">if</span><span class="s2"> </span><span class="s4">(</span><span class="s2">password </span><span class="s4">!==</span><span class="s2"> </span><span class="s1">null</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span>alert</span><span class="s4">(</span><span class="s5">"Falsches Passwort."</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s1">return</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p4"><span class="s2"><span class="Apple-converted-space">        </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">if</span><span class="s2"> </span><span class="s4">(</span><span class="s2">showForm</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p6"><span class="s6"><span class="Apple-converted-space">            </span></span><span class="s2">// If form is open, clicking again should close it and cancel any edit</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setShowForm</span><span class="s4">(</span><span class="s1">false</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setEditingEntry</span><span class="s4">(</span><span class="s1">null</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span><span class="s2"> </span><span class="s1">else</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p6"><span class="s6"><span class="Apple-converted-space">            </span></span><span class="s2">// If form is closed, open it for a new entry</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setEditingEntry</span><span class="s4">(</span><span class="s1">null</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setShowForm</span><span class="s4">(</span><span class="s1">true</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">};</span></p>
<p class="p4"><span class="s2"><span class="Apple-converted-space">    </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> handleLogout </span><span class="s4">=</span><span class="s2"> </span><span class="s4">()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>sessionStorage</span><span class="s4">.</span><span class="s2">removeItem</span><span class="s4">(</span><span class="s5">'motionvation_auth'</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setIsAuthenticated</span><span class="s4">(</span><span class="s1">false</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setShowForm</span><span class="s4">(</span><span class="s1">false</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>setEditingEntry</span><span class="s4">(</span><span class="s1">null</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">};</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">    </span></span><span class="s2">return</span><span class="s6"> </span><span class="s4">(</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">        </span></span><span class="s4">&lt;</span><span class="s6">div className</span><span class="s4">=</span><span class="s2">"bg-comic-blue min-h-screen font-sans text-comic-dark"</span><span class="s4">&gt;</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">            </span></span><span class="s4">&lt;</span><span class="s6">div className</span><span class="s4">=</span><span class="s2">"container mx-auto p-4 max-w-2xl"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s3">Header</span><span class="s2"> /&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s3">SummaryDashboard</span><span class="s2"> summary</span><span class="s4">={</span><span class="s2">summary</span><span class="s4">}</span><span class="s2"> /&gt;</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s2">div className</span><span class="s4">=</span><span class="s5">"text-center my-6"</span><span class="s4">&gt;</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">                   </span></span><span class="s4">&lt;</span><span class="s6">div className</span><span class="s4">=</span><span class="s2">"flex justify-center items-center gap-4"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">button</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span>onClick</span><span class="s4">={</span><span class="s2">handleToggleFormClick</span><span class="s4">}</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">                            </span>className</span><span class="s4">=</span><span class="s2">"bg-comic-yellow text-comic-dark font-display text-2xl px-6 py-2 rounded-lg border-4 border-comic-dark shadow-[4px_4px_0px_#2C2A29] hover:shadow-none hover:translate-x-1 hover:translate-y-1 transform transition-all duration-150 flex items-center justify-center gap-2"</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span>aria</span><span class="s4">-</span><span class="s2">haspopup</span><span class="s4">={!</span><span class="s2">isAuthenticated</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span>aria</span><span class="s4">-</span><span class="s2">expanded</span><span class="s4">={</span><span class="s2">showForm</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span></span><span class="s4">&lt;</span><span class="s3">PlusCircle</span><span class="s2"> className</span><span class="s4">=</span><span class="s5">"w-6 h-6"</span><span class="s2"> /&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span></span><span class="s4">{</span><span class="s2">showForm </span><span class="s4">?</span><span class="s2"> </span><span class="s5">'Eingabe abbrechen'</span><span class="s2"> </span><span class="s4">:</span><span class="s2"> </span><span class="s5">'Neuer Eintrag'</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;/</span><span class="s2">button</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">{</span><span class="s2">isAuthenticated </span><span class="s4">&amp;&amp;</span><span class="s2"> </span><span class="s4">(</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                             </span></span><span class="s4">&lt;</span><span class="s2">button</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                                </span>onClick</span><span class="s4">={</span><span class="s2">handleLogout</span><span class="s4">}</span></p>
<p class="p3"><span class="s6"><span class="Apple-converted-space">                                </span>className</span><span class="s4">=</span><span class="s2">"bg-red-500 text-white p-3 rounded-full border-4 border-comic-dark shadow-[4px_4px_0px_#2C2A29] hover:shadow-none hover:translate-x-1 hover:translate-y-1 transform transition-all duration-150"</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                                </span>aria</span><span class="s4">-</span><span class="s2">label</span><span class="s4">=</span><span class="s5">"Logout"</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                             </span></span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                                </span></span><span class="s4">&lt;</span><span class="s3">LogOut</span><span class="s2"> className</span><span class="s4">=</span><span class="s5">"w-6 h-6"</span><span class="s2"> /&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                             </span></span><span class="s4">&lt;/</span><span class="s2">button</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">)}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">{</span><span class="s2">showForm </span><span class="s4">&amp;&amp;</span><span class="s2"> isAuthenticated </span><span class="s4">&amp;&amp;</span><span class="s2"> </span><span class="s4">(</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">div className</span><span class="s4">=</span><span class="s5">"mb-8 animate-fade-in"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s3">EntryForm</span><span class="s2"><span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span>onSaveEntry</span><span class="s4">={</span><span class="s2">handleSaveEntry</span><span class="s4">}</span><span class="s2"><span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span>entryToEdit</span><span class="s4">={</span><span class="s2">editingEntry</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                            </span>onCancel</span><span class="s4">={()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span><span class="s2">setShowForm</span><span class="s4">(</span><span class="s1">false</span><span class="s4">);</span><span class="s2"> setEditingEntry</span><span class="s4">(</span><span class="s1">null</span><span class="s4">);}}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span>/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">)}</span></p>
<p class="p4"><span class="s2"><span class="Apple-converted-space">                </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s3">Logbook</span><span class="s2"><span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span>entries</span><span class="s4">={</span><span class="s2">entries</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span>isAuthenticated</span><span class="s4">={</span><span class="s2">isAuthenticated</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span>onEdit</span><span class="s4">={</span><span class="s2">handleEdit</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span>onDelete</span><span class="s4">={</span><span class="s2">handleDelete</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span>/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s3">Footer</span><span class="s2"> /&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">);</span></p>
<p class="p5"><span class="s2">};</span></p>
<p class="p4"><span class="s2"></span><br></p>
<p class="p7"><span class="s2">export</span><span class="s6"> </span><span class="s2">default</span><span class="s6"> </span><span class="s3">App</span><span class="s4">;</span></p>
<p class="p4"><span class="s2"></span><br></p>
</body>
</html>
