<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2575.7">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #4689cc; -webkit-text-stroke: #4689cc; background-color: #171717}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #36c0a0; -webkit-text-stroke: #36c0a0; background-color: #171717}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #cacaca; -webkit-text-stroke: #cacaca; background-color: #171717; min-height: 14.0px}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #cacaca; -webkit-text-stroke: #cacaca; background-color: #171717}
    p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #d4d4d4; -webkit-text-stroke: #d4d4d4; background-color: #171717}
    p.p6 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #c27e65; -webkit-text-stroke: #c27e65; background-color: #171717}
    span.s1 {font-kerning: none}
    span.s2 {font-kerning: none; color: #cacaca; -webkit-text-stroke: 0px #cacaca}
    span.s3 {font-kerning: none; color: #36c0a0; -webkit-text-stroke: 0px #36c0a0}
    span.s4 {font-kerning: none; color: #c27e65; -webkit-text-stroke: 0px #c27e65}
    span.s5 {font-kerning: none; color: #d4d4d4; -webkit-text-stroke: 0px #d4d4d4}
    span.s6 {font-kerning: none; color: #4689cc; -webkit-text-stroke: 0px #4689cc}
    span.s7 {font-kerning: none; color: #ee2e38; -webkit-text-stroke: 0px #ee2e38}
  </style>
</head>
<body>
<p class="p1"><span class="s1">import</span><span class="s2"> </span><span class="s3">React</span><span class="s2"> </span><span class="s1">from</span><span class="s2"> </span><span class="s4">'react'</span><span class="s5">;</span></p>
<p class="p1"><span class="s1">import</span><span class="s2"> </span><span class="s1">type</span><span class="s2"> </span><span class="s5">{</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s2"> </span><span class="s5">}</span><span class="s2"> </span><span class="s1">from</span><span class="s2"> </span><span class="s4">'../types'</span><span class="s5">;</span></p>
<p class="p2"><span class="s6">import</span><span class="s2"> </span><span class="s5">{</span><span class="s2"> </span><span class="s1">Calendar</span><span class="s5">,</span><span class="s2"> </span><span class="s1">TrendingUp</span><span class="s5">,</span><span class="s2"> </span><span class="s1">Award</span><span class="s5">,</span><span class="s2"> </span><span class="s1">Zap</span><span class="s5">,</span><span class="s2"> </span><span class="s1">Pencil</span><span class="s5">,</span><span class="s2"> </span><span class="s1">Trash2</span><span class="s2"> </span><span class="s5">}</span><span class="s2"> </span><span class="s6">from</span><span class="s2"> </span><span class="s4">'lucide-react'</span><span class="s5">;</span></p>
<p class="p3"><span class="s1"></span><br></p>
<p class="p2"><span class="s6">interface</span><span class="s2"> </span><span class="s1">DailyEntryCardProps</span><span class="s2"> </span><span class="s5">{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>entry</span><span class="s5">:</span><span class="s1"> </span><span class="s3">DailyEntry</span><span class="s5">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>isAuthenticated</span><span class="s5">:</span><span class="s1"> </span><span class="s6">boolean</span><span class="s5">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>onEdit</span><span class="s5">:</span><span class="s1"> </span><span class="s5">(</span><span class="s1">entry</span><span class="s5">:</span><span class="s1"> </span><span class="s3">DailyEntry</span><span class="s5">)</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> </span><span class="s6">void</span><span class="s5">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>onDelete</span><span class="s5">:</span><span class="s1"> </span><span class="s5">(</span><span class="s1">date</span><span class="s5">:</span><span class="s1"> </span><span class="s6">string</span><span class="s5">)</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> </span><span class="s6">void</span><span class="s5">;</span></p>
<p class="p5"><span class="s1">}</span></p>
<p class="p3"><span class="s1"></span><br></p>
<p class="p4"><span class="s6">export</span><span class="s1"> </span><span class="s6">const</span><span class="s1"> </span><span class="s3">DailyEntryCard</span><span class="s5">:</span><span class="s1"> </span><span class="s3">React</span><span class="s5">.</span><span class="s3">FC</span><span class="s5">&lt;</span><span class="s3">DailyEntryCardProps</span><span class="s5">&gt;</span><span class="s1"> </span><span class="s5">=</span><span class="s1"> </span><span class="s5">({</span><span class="s1"> entry</span><span class="s5">,</span><span class="s1"> isAuthenticated</span><span class="s5">,</span><span class="s1"> onEdit</span><span class="s5">,</span><span class="s1"> onDelete </span><span class="s5">})</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> </span><span class="s5">{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s6">const</span><span class="s1"> formattedDate </span><span class="s5">=</span><span class="s1"> </span><span class="s6">new</span><span class="s1"> </span><span class="s3">Date</span><span class="s5">(</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">date</span><span class="s5">).</span><span class="s1">toLocaleDateString</span><span class="s5">(</span><span class="s4">'de-DE'</span><span class="s5">,</span><span class="s1"> </span><span class="s5">{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>weekday</span><span class="s5">:</span><span class="s1"> </span><span class="s4">'long'</span><span class="s5">,</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>year</span><span class="s5">:</span><span class="s1"> </span><span class="s4">'numeric'</span><span class="s5">,</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>month</span><span class="s5">:</span><span class="s1"> </span><span class="s4">'long'</span><span class="s5">,</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>day</span><span class="s5">:</span><span class="s1"> </span><span class="s4">'numeric'</span><span class="s5">,</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s5">});</span></p>
<p class="p3"><span class="s1"></span><br></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s6">const</span><span class="s1"> </span><span class="s3">ActionButton</span><span class="s5">:</span><span class="s1"> </span><span class="s3">React</span><span class="s5">.</span><span class="s3">FC</span><span class="s5">&lt;{</span><span class="s1"> onClick</span><span class="s5">:</span><span class="s1"> </span><span class="s5">()</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> </span><span class="s6">void</span><span class="s5">;</span><span class="s1"> children</span><span class="s5">:</span><span class="s1"> </span><span class="s3">React</span><span class="s5">.</span><span class="s3">ReactNode</span><span class="s5">;</span><span class="s1"> className?: </span><span class="s6">string</span><span class="s5">,</span><span class="s1"> </span><span class="s4">'aria-label'</span><span class="s5">:</span><span class="s1"> </span><span class="s6">string</span><span class="s1"> </span><span class="s5">}&gt;</span><span class="s1"> </span><span class="s5">=</span><span class="s1"> </span><span class="s5">({</span><span class="s1"> onClick</span><span class="s5">,</span><span class="s1"> children</span><span class="s5">,</span><span class="s1"> className</span><span class="s5">,</span><span class="s1"> </span><span class="s4">'aria-label'</span><span class="s5">:</span><span class="s1"> ariaLabel </span><span class="s5">})</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> </span><span class="s5">(</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span></span><span class="s5">&lt;</span><span class="s1">button</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">            </span>onClick</span><span class="s5">={</span><span class="s1">onClick</span><span class="s5">}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">            </span>aria</span><span class="s5">-</span><span class="s1">label</span><span class="s5">={</span><span class="s1">ariaLabel</span><span class="s5">}</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">            </span>className</span><span class="s5">={</span><span class="s1">`p-2 rounded-full border-2 border-comic-dark transform transition-transform hover:scale-110 </span><span class="s5">${</span><span class="s2">className</span><span class="s5">}</span><span class="s1">`</span><span class="s5">}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span></span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">            </span></span><span class="s5">{</span><span class="s1">children</span><span class="s5">}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span></span><span class="s5">&lt;/</span><span class="s1">button</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s5">);</span></p>
<p class="p3"><span class="s1"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">return</span><span class="s2"> </span><span class="s5">(</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s5">&lt;</span><span class="s2">div className</span><span class="s5">=</span><span class="s1">"bg-comic-cream rounded-xl border-4 border-comic-dark shadow-[8px_8px_0px_#2C2A29] overflow-hidden transform hover:-translate-y-1 transition-transform duration-150"</span><span class="s5">&gt;</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s5">&lt;</span><span class="s2">div className</span><span class="s5">=</span><span class="s1">"bg-comic-dark text-comic-cream p-4 flex items-center gap-4 relative"</span><span class="s5">&gt;</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s5">&lt;</span><span class="s3">Calendar</span><span class="s2"> className</span><span class="s5">=</span><span class="s1">"w-8 h-8 text-comic-yellow flex-shrink-0"</span><span class="s2">/&gt;</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s5">&lt;</span><span class="s2">h3 className</span><span class="s5">=</span><span class="s1">"font-display text-2xl sm:text-3xl tracking-wider"</span><span class="s5">&gt;{</span><span class="s2">formattedDate</span><span class="s5">}&lt;/</span><span class="s2">h3</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">{</span><span class="s1">isAuthenticated </span><span class="s5">&amp;&amp;</span><span class="s1"> </span><span class="s5">(</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;</span><span class="s2">div className</span><span class="s5">=</span><span class="s1">"absolute top-1/2 right-3 -translate-y-1/2 flex gap-2"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s3">ActionButton</span><span class="s1"> onClick</span><span class="s5">={()</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> onEdit</span><span class="s5">(</span><span class="s1">entry</span><span class="s5">)}</span><span class="s1"> className</span><span class="s5">=</span><span class="s4">"bg-comic-blue text-white"</span><span class="s1"> aria</span><span class="s5">-</span><span class="s1">label</span><span class="s5">=</span><span class="s4">"Eintrag bearbeiten"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                           </span></span><span class="s5">&lt;</span><span class="s3">Pencil</span><span class="s1"> className</span><span class="s5">=</span><span class="s4">"w-5 h-5"</span><span class="s1"> /&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;/</span><span class="s3">ActionButton</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s3">ActionButton</span><span class="s1"> onClick</span><span class="s5">={()</span><span class="s1"> </span><span class="s5">=&gt;</span><span class="s1"> onDelete</span><span class="s5">(</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">date</span><span class="s5">)}</span><span class="s1"> className</span><span class="s5">=</span><span class="s4">"bg-red-500 text-white"</span><span class="s1"> aria</span><span class="s5">-</span><span class="s1">label</span><span class="s5">=</span><span class="s4">"Eintrag löschen"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                            </span></span><span class="s5">&lt;</span><span class="s3">Trash2</span><span class="s1"> className</span><span class="s5">=</span><span class="s4">"w-5 h-5"</span><span class="s1"> /&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;/</span><span class="s3">ActionButton</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">)}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">            </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">            </span></span><span class="s5">&lt;</span><span class="s1">div className</span><span class="s5">=</span><span class="s4">"p-6"</span><span class="s5">&gt;</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s5">&lt;</span><span class="s2">div className</span><span class="s5">=</span><span class="s1">"grid md:grid-cols-3 gap-6 mb-6 text-center"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;</span><span class="s1">div className</span><span class="s5">=</span><span class="s4">"flex flex-col items-center"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s3">TrendingUp</span><span class="s1"> className</span><span class="s5">=</span><span class="s4">"w-10 h-10 text-comic-blue mb-2"</span><span class="s1"> /&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">span className</span><span class="s5">=</span><span class="s4">"font-bold text-xl"</span><span class="s5">&gt;</span><span class="s3">Schritte</span><span class="s5">&lt;/</span><span class="s1">span</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">span className</span><span class="s5">=</span><span class="s4">"font-display text-3xl sm:text-4xl text-comic-blue"</span><span class="s5">&gt;{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">steps</span><span class="s5">.</span><span class="s1">toLocaleString</span><span class="s5">(</span><span class="s4">'de-DE'</span><span class="s5">)}&lt;/</span><span class="s1">span</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;</span><span class="s1">div className</span><span class="s5">=</span><span class="s4">"flex flex-col items-center"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s3">Award</span><span class="s1"> className</span><span class="s5">=</span><span class="s4">"w-10 h-10 text-comic-green mb-2"</span><span class="s1"> /&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">span className</span><span class="s5">=</span><span class="s4">"font-bold text-xl"</span><span class="s5">&gt;</span><span class="s3">Liegest</span><span class="s7">ü</span><span class="s1">tze</span><span class="s5">&lt;/</span><span class="s1">span</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">span className</span><span class="s5">=</span><span class="s4">"font-display text-3xl sm:text-4xl text-comic-green"</span><span class="s5">&gt;{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">pushups</span><span class="s5">.</span><span class="s1">toLocaleString</span><span class="s5">(</span><span class="s4">'de-DE'</span><span class="s5">)}&lt;/</span><span class="s1">span</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;</span><span class="s1">div className</span><span class="s5">=</span><span class="s4">"flex flex-col items-center"</span><span class="s5">&gt;</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s3">Zap</span><span class="s2"> className</span><span class="s5">=</span><span class="s1">"w-10 h-10 text-comic-yellow mb-2 stroke-comic-dark"</span><span class="s2"> /&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">span className</span><span class="s5">=</span><span class="s4">"font-bold text-xl"</span><span class="s5">&gt;</span><span class="s3">Klimmz</span><span class="s7">ü</span><span class="s1">ge</span><span class="s5">&lt;/</span><span class="s1">span</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">span className</span><span class="s5">=</span><span class="s4">"font-display text-3xl sm:text-4xl"</span><span class="s1"> style</span><span class="s5">={{</span><span class="s1">color</span><span class="s5">:</span><span class="s1"> </span><span class="s4">"#E57A00"</span><span class="s5">}}&gt;{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">pullups</span><span class="s5">.</span><span class="s1">toLocaleString</span><span class="s5">(</span><span class="s4">'de-DE'</span><span class="s5">)}&lt;/</span><span class="s1">span</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p3"><span class="s1"></span><br></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">optionalExerciseName </span><span class="s5">&amp;&amp;</span><span class="s1"> entry</span><span class="s5">.</span><span class="s1">optionalExerciseReps </span><span class="s5">&amp;&amp;</span><span class="s1"> </span><span class="s5">(</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;</span><span class="s2">div className</span><span class="s5">=</span><span class="s1">"text-center mb-6 bg-white/50 p-3 rounded-lg border-2 border-comic-dark border-dashed"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s1">p className</span><span class="s5">=</span><span class="s4">"font-bold text-lg"</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                           </span></span><span class="s3">Extra</span><span class="s5">:</span><span class="s1"> </span><span class="s5">{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">optionalExerciseReps</span><span class="s5">.</span><span class="s1">toLocaleString</span><span class="s5">(</span><span class="s4">'de-DE'</span><span class="s5">)}</span><span class="s1"> </span><span class="s5">{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">optionalExerciseName</span><span class="s5">}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;/</span><span class="s1">p</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">)}</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">                </span></span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">{</span><span class="s1">entry</span><span class="s5">.</span><span class="s1">comment </span><span class="s5">&amp;&amp;</span><span class="s1"> </span><span class="s5">(</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;</span><span class="s1">div className</span><span class="s5">=</span><span class="s4">"mt-4"</span><span class="s5">&gt;</span></p>
<p class="p6"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s5">&lt;</span><span class="s2">p className</span><span class="s5">=</span><span class="s1">"italic text-gray-800 bg-white p-4 rounded-lg border-2 border-comic-dark"</span><span class="s5">&gt;</span><span class="s1">"{entry.comment}"</span><span class="s5">&lt;/</span><span class="s2">p</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                    </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">                </span></span><span class="s5">)}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">            </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span></span><span class="s5">&lt;/</span><span class="s1">div</span><span class="s5">&gt;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s5">);</span></p>
<p class="p5"><span class="s1">};</span></p>
<p class="p3"><span class="s1"></span><br></p>
</body>
</html>
