<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2575.7">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #bebebe; -webkit-text-stroke: #bebebe; background-color: #121212}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #3874c0; -webkit-text-stroke: #3874c0; background-color: #121212}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #bebebe; -webkit-text-stroke: #bebebe; background-color: #121212; min-height: 14.0px}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #30b68f; -webkit-text-stroke: #30b68f; background-color: #121212}
    p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #cacaca; -webkit-text-stroke: #cacaca; background-color: #121212}
    p.p6 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #3f6a2f; -webkit-text-stroke: #3f6a2f; background-color: #121212}
    p.p7 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Menlo; color: #b36a52; -webkit-text-stroke: #b36a52; background-color: #121212}
    span.s1 {font-kerning: none; color: #3874c0; -webkit-text-stroke: 0px #3874c0}
    span.s2 {font-kerning: none}
    span.s3 {font-kerning: none; color: #30b68f; -webkit-text-stroke: 0px #30b68f}
    span.s4 {font-kerning: none; color: #cacaca; -webkit-text-stroke: 0px #cacaca}
    span.s5 {font-kerning: none; color: #b36a52; -webkit-text-stroke: 0px #b36a52}
    span.s6 {font-kerning: none; color: #bebebe; -webkit-text-stroke: 0px #bebebe}
    span.s7 {font-kerning: none; color: #97bb86; -webkit-text-stroke: 0px #97bb86}
    span.s8 {font-kerning: none; color: #e7142b; -webkit-text-stroke: 0px #e7142b}
  </style>
</head>
<body>
<p class="p1"><span class="s1">import</span><span class="s2"> </span><span class="s3">React</span><span class="s4">,</span><span class="s2"> </span><span class="s4">{</span><span class="s2"> useState</span><span class="s4">,</span><span class="s2"> useEffect </span><span class="s4">}</span><span class="s2"> </span><span class="s1">from</span><span class="s2"> </span><span class="s5">'react'</span><span class="s4">;</span></p>
<p class="p2"><span class="s2">import</span><span class="s6"> </span><span class="s2">type</span><span class="s6"> </span><span class="s4">{</span><span class="s6"> </span><span class="s3">DailyEntry</span><span class="s6"> </span><span class="s4">}</span><span class="s6"> </span><span class="s2">from</span><span class="s6"> </span><span class="s5">'../types'</span><span class="s4">;</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p4"><span class="s1">interface</span><span class="s6"> </span><span class="s2">EntryFormProps</span><span class="s6"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span>onSaveEntry</span><span class="s4">:</span><span class="s2"> </span><span class="s4">(</span><span class="s2">entry</span><span class="s4">:</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s4">)</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s1">void</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span>entryToEdit</span><span class="s4">:</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s2"> </span><span class="s4">|</span><span class="s2"> </span><span class="s1">null</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span>onCancel</span><span class="s4">:</span><span class="s2"> </span><span class="s4">()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s1">void</span><span class="s4">;</span></p>
<p class="p5"><span class="s2">}</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p1"><span class="s1">export</span><span class="s2"> </span><span class="s1">const</span><span class="s2"> </span><span class="s3">EntryForm</span><span class="s4">:</span><span class="s2"> </span><span class="s3">React</span><span class="s4">.</span><span class="s3">FC</span><span class="s4">&lt;</span><span class="s3">EntryFormProps</span><span class="s4">&gt;</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> </span><span class="s4">({</span><span class="s2"> onSaveEntry</span><span class="s4">,</span><span class="s2"> entryToEdit</span><span class="s4">,</span><span class="s2"> onCancel </span><span class="s4">})</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">date</span><span class="s4">,</span><span class="s2"> setDate</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s1">new</span><span class="s2"> </span><span class="s3">Date</span><span class="s4">().</span><span class="s2">toISOString</span><span class="s4">().</span><span class="s2">split</span><span class="s4">(</span><span class="s5">'T'</span><span class="s4">)[</span><span class="s7">0</span><span class="s4">]);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">steps</span><span class="s4">,</span><span class="s2"> setSteps</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">pushups</span><span class="s4">,</span><span class="s2"> setPushups</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">pullups</span><span class="s4">,</span><span class="s2"> setPullups</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">optionalExerciseName</span><span class="s4">,</span><span class="s2"> setOptionalExerciseName</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">optionalExerciseReps</span><span class="s4">,</span><span class="s2"> setOptionalExerciseReps</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> </span><span class="s4">[</span><span class="s2">comment</span><span class="s4">,</span><span class="s2"> setComment</span><span class="s4">]</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> useState</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p3"><span class="s2"><span class="Apple-converted-space">    </span></span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> isEditing </span><span class="s4">=</span><span class="s2"> </span><span class="s4">!!</span><span class="s2">entryToEdit</span><span class="s4">;</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span>useEffect</span><span class="s4">(()</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">if</span><span class="s2"> </span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setDate</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">date</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setSteps</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">steps</span><span class="s4">.</span><span class="s2">toString</span><span class="s4">());</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setPushups</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">pushups</span><span class="s4">.</span><span class="s2">toString</span><span class="s4">());</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setPullups</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">pullups</span><span class="s4">.</span><span class="s2">toString</span><span class="s4">());</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setOptionalExerciseName</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">optionalExerciseName </span><span class="s4">||</span><span class="s2"> </span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setOptionalExerciseReps</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">optionalExerciseReps</span><span class="s4">?.</span><span class="s2">toString</span><span class="s4">()</span><span class="s2"> </span><span class="s4">||</span><span class="s2"> </span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setComment</span><span class="s4">(</span><span class="s2">entryToEdit</span><span class="s4">.</span><span class="s2">comment </span><span class="s4">||</span><span class="s2"> </span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span><span class="s2"> </span><span class="s1">else</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p6"><span class="s6"><span class="Apple-converted-space">            </span></span><span class="s2">// Reset form for new entry</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setDate</span><span class="s4">(</span><span class="s1">new</span><span class="s2"> </span><span class="s3">Date</span><span class="s4">().</span><span class="s2">toISOString</span><span class="s4">().</span><span class="s2">split</span><span class="s4">(</span><span class="s5">'T'</span><span class="s4">)[</span><span class="s7">0</span><span class="s4">]);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setSteps</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setPushups</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setPullups</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setOptionalExerciseName</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setOptionalExerciseReps</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>setComment</span><span class="s4">(</span><span class="s5">''</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">},</span><span class="s2"> </span><span class="s4">[</span><span class="s2">entryToEdit</span><span class="s4">]);</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s2"> handleSubmit </span><span class="s4">=</span><span class="s2"> </span><span class="s4">(</span><span class="s2">e</span><span class="s4">:</span><span class="s2"> </span><span class="s3">React</span><span class="s4">.</span><span class="s3">FormEvent</span><span class="s4">)</span><span class="s2"> </span><span class="s4">=&gt;</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>e</span><span class="s4">.</span><span class="s2">preventDefault</span><span class="s4">();</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">if</span><span class="s2"> </span><span class="s4">(!</span><span class="s2">date </span><span class="s4">||</span><span class="s2"> </span><span class="s4">!</span><span class="s2">steps </span><span class="s4">||</span><span class="s2"> </span><span class="s4">!</span><span class="s2">pushups </span><span class="s4">||</span><span class="s2"> </span><span class="s4">!</span><span class="s2">pullups</span><span class="s4">)</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">            </span>alert</span><span class="s4">(</span><span class="s2">'Bitte fülle die erforderlichen Felder aus.'</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s1">return</span><span class="s4">;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">}</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">const</span><span class="s2"> newEntry</span><span class="s4">:</span><span class="s2"> </span><span class="s3">DailyEntry</span><span class="s2"> </span><span class="s4">=</span><span class="s2"> </span><span class="s4">{</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>date</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>steps</span><span class="s4">:</span><span class="s2"> parseInt</span><span class="s4">(</span><span class="s2">steps</span><span class="s4">,</span><span class="s2"> </span><span class="s7">10</span><span class="s4">),</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>pushups</span><span class="s4">:</span><span class="s2"> parseInt</span><span class="s4">(</span><span class="s2">pushups</span><span class="s4">,</span><span class="s2"> </span><span class="s7">10</span><span class="s4">),</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>pullups</span><span class="s4">:</span><span class="s2"> parseInt</span><span class="s4">(</span><span class="s2">pullups</span><span class="s4">,</span><span class="s2"> </span><span class="s7">10</span><span class="s4">),</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>optionalExerciseName</span><span class="s4">:</span><span class="s2"> optionalExerciseName </span><span class="s4">||</span><span class="s2"> </span><span class="s1">undefined</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>optionalExerciseReps</span><span class="s4">:</span><span class="s2"> optionalExerciseReps </span><span class="s4">?</span><span class="s2"> parseInt</span><span class="s4">(</span><span class="s2">optionalExerciseReps</span><span class="s4">,</span><span class="s2"> </span><span class="s7">10</span><span class="s4">)</span><span class="s2"> </span><span class="s4">:</span><span class="s2"> </span><span class="s1">undefined</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span>comment</span><span class="s4">:</span><span class="s2"> comment </span><span class="s4">||</span><span class="s2"> </span><span class="s1">undefined</span><span class="s4">,</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">};</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span>onSaveEntry</span><span class="s4">(</span><span class="s2">newEntry</span><span class="s4">);</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">};</span></p>
<p class="p3"><span class="s2"><span class="Apple-converted-space">    </span></span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s6"> inputClasses </span><span class="s4">=</span><span class="s6"> </span><span class="s2">"w-full p-3 rounded-lg border-4 border-comic-dark bg-white focus:outline-none focus:ring-4 focus:ring-comic-yellow transition-shadow disabled:bg-gray-200 disabled:cursor-not-allowed"</span><span class="s4">;</span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">    </span></span><span class="s1">const</span><span class="s6"> labelClasses </span><span class="s4">=</span><span class="s6"> </span><span class="s2">"block font-bold text-lg mb-1"</span><span class="s4">;</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p2"><span class="s6"><span class="Apple-converted-space">    </span></span><span class="s2">return</span><span class="s6"> </span><span class="s4">(</span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">        </span></span><span class="s4">&lt;</span><span class="s6">div className</span><span class="s4">=</span><span class="s2">"bg-comic-cream p-6 rounded-xl border-4 border-comic-dark shadow-[8px_8px_0px_#2C2A29] mb-8"</span><span class="s4">&gt;</span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">            </span></span><span class="s4">&lt;</span><span class="s6">h2 className</span><span class="s4">=</span><span class="s2">"font-display text-3xl sm:text-4xl text-center mb-4 text-comic-green tracking-wider"</span><span class="s4">&gt;</span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">                </span></span><span class="s4">{</span><span class="s6">isEditing </span><span class="s4">?</span><span class="s6"> </span><span class="s2">'Eintrag bearbeiten'</span><span class="s6"> </span><span class="s4">:</span><span class="s6"> </span><span class="s2">'Neuer Eintrag'</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s4">&lt;/</span><span class="s2">h2</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s4">&lt;</span><span class="s2">form onSubmit</span><span class="s4">={</span><span class="s2">handleSubmit</span><span class="s4">}</span><span class="s2"> className</span><span class="s4">=</span><span class="s5">"space-y-4"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"date"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Datum</span><span class="s4">&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">input </span><span class="s1">type</span><span class="s4">=</span><span class="s5">"date"</span><span class="s2"> id</span><span class="s4">=</span><span class="s5">"date"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">date</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setDate</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> required disabled</span><span class="s4">={</span><span class="s2">isEditing</span><span class="s4">}</span><span class="s2"> /&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s2">div className</span><span class="s4">=</span><span class="s5">"grid md:grid-cols-3 gap-4"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"steps"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Schritte</span><span class="s4">&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">input </span><span class="s1">type</span><span class="s4">=</span><span class="s5">"number"</span><span class="s2"> id</span><span class="s4">=</span><span class="s5">"steps"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">steps</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setSteps</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> placeholder</span><span class="s4">=</span><span class="s5">"z.B. 20000"</span><span class="s2"> required/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                     </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"pushups"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Liegest</span><span class="s8">ü</span><span class="s2">tze</span><span class="s4">&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">input </span><span class="s1">type</span><span class="s4">=</span><span class="s5">"number"</span><span class="s2"> id</span><span class="s4">=</span><span class="s5">"pushups"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">pushups</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setPushups</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> placeholder</span><span class="s4">=</span><span class="s5">"z.B. 320"</span><span class="s2"> required/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                     </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"pullups"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Klimmz</span><span class="s8">ü</span><span class="s2">ge</span><span class="s4">&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">input </span><span class="s1">type</span><span class="s4">=</span><span class="s5">"number"</span><span class="s2"> id</span><span class="s4">=</span><span class="s5">"pullups"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">pullups</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setPullups</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> placeholder</span><span class="s4">=</span><span class="s5">"z.B. 75"</span><span class="s2"> required/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s2">div className</span><span class="s4">=</span><span class="s5">"grid md:grid-cols-2 gap-4"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"opt-exercise"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Weitere</span><span class="s2"> </span><span class="s8">Ü</span><span class="s2">bung </span><span class="s4">(</span><span class="s3">Optional</span><span class="s4">)&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">input </span><span class="s1">type</span><span class="s4">=</span><span class="s5">"text"</span><span class="s2"> id</span><span class="s4">=</span><span class="s5">"opt-exercise"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">optionalExerciseName</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setOptionalExerciseName</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> placeholder</span><span class="s4">=</span><span class="s5">"z.B. Squats"</span><span class="s2">/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                     </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"opt-reps"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Wiederholungen</span><span class="s4">&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                        </span></span><span class="s4">&lt;</span><span class="s2">input </span><span class="s1">type</span><span class="s4">=</span><span class="s5">"number"</span><span class="s2"> id</span><span class="s4">=</span><span class="s5">"opt-reps"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">optionalExerciseReps</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setOptionalExerciseReps</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> placeholder</span><span class="s4">=</span><span class="s5">"z.B. 100"</span><span class="s2">/&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">label htmlFor</span><span class="s4">=</span><span class="s5">"comment"</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">labelClasses</span><span class="s4">}&gt;</span><span class="s3">Tages</span><span class="s2"> </span><span class="s3">Kommentar</span><span class="s2"> </span><span class="s4">(</span><span class="s3">Optional</span><span class="s4">)&lt;/</span><span class="s2">label</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">&lt;</span><span class="s2">textarea id</span><span class="s4">=</span><span class="s5">"comment"</span><span class="s2"> value</span><span class="s4">={</span><span class="s2">comment</span><span class="s4">}</span><span class="s2"> onChange</span><span class="s4">={</span><span class="s2">e </span><span class="s4">=&gt;</span><span class="s2"> setComment</span><span class="s4">(</span><span class="s2">e</span><span class="s4">.</span><span class="s2">target</span><span class="s4">.</span><span class="s2">value</span><span class="s4">)}</span><span class="s2"> className</span><span class="s4">={</span><span class="s2">inputClasses</span><span class="s4">}</span><span class="s2"> rows</span><span class="s4">={</span><span class="s7">3</span><span class="s4">}</span><span class="s2"> placeholder</span><span class="s4">=</span><span class="s5">"Wie war der Tag?"</span><span class="s2">&gt;&lt;/textarea</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p7"><span class="s6"><span class="Apple-converted-space">                 </span></span><span class="s4">&lt;</span><span class="s6">button </span><span class="s1">type</span><span class="s4">=</span><span class="s2">"submit"</span><span class="s6"> className</span><span class="s4">=</span><span class="s2">"w-full bg-comic-green text-white font-display text-2xl px-6 py-2 rounded-lg border-4 border-comic-dark shadow-[4px_4px_0px_#2C2A29] hover:shadow-none hover:translate-x-1 hover:translate-y-1 transform transition-all duration-150"</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                    </span></span><span class="s4">{</span><span class="s2">isEditing </span><span class="s4">?</span><span class="s2"> </span><span class="s5">'Aktualisieren'</span><span class="s2"> </span><span class="s4">:</span><span class="s2"> </span><span class="s5">'Speichern'</span><span class="s4">}</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">                </span></span><span class="s4">&lt;/</span><span class="s2">button</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">            </span></span><span class="s4">&lt;/</span><span class="s2">form</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">&lt;/</span><span class="s2">div</span><span class="s4">&gt;</span></p>
<p class="p1"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s4">);</span></p>
<p class="p5"><span class="s2">};</span></p>
<p class="p3"><span class="s2"></span><br></p>
<p class="p3"><span class="s2"></span><br></p>
</body>
</html>
